import type { Metadata } from 'next';
import { PageIntro } from '@/components/PageSections';
import { site } from '@/data/site';

export const metadata: Metadata = { title: 'צרו קשר', description: 'לשיחה, שליחת תוכניות או תיאום פגישה לעבודות אלומיניום.' };

export default function ContactPage() {
  return <main><div className='container-main'><PageIntro eyebrow='צרו קשר' title='צרו קשר' text='לשיחה, שליחת תוכניות או תיאום פגישה לעבודות אלומיניום.' /><section className='section-shell grid-3'>{[['טלפון',site.phone,'התקשרו',site.phoneHref],['וואטסאפ','שליחת הודעה, תמונות או תוכניות','שלחו וואטסאפ',site.whatsapp],['מייל','לפניות, תוכניות ומפרטים','שליחת מייל',site.email]].map(([title,text,cta,href])=><article className='feature-card' key={String(title)}><h2>{title}</h2><p>{text}</p><a className='btn btn-outline' href={String(href)}>{cta}</a></article>)}</section><section className='section-shell'><form className='feature-card contact-form'><label className='field'>שם מלא<input name='name' type='text' /></label><label className='field'>טלפון<input name='phone' type='tel' /></label><label className='field'>סוג עבודה<select name='projectType' defaultValue=''><option value='' disabled>בחרו</option><option>חלונות וויטרינות</option><option>תריסים והצללה</option><option>פרגולות</option><option>גדרות, שערים וחיפויים</option><option>מעקות זכוכית ומקלחונים</option><option>אדריכל / קבלן / מפקח</option></select></label><label className='field'>שלב הפרויקט<select name='projectStage' defaultValue=''><option value='' disabled>בחרו</option><option>תכנון ראשוני</option><option>לפני היתר</option><option>במהלך שלד</option><option>לפני גמרים</option><option>שיפוץ קיים</option><option>לא בטוח</option></select></label><label className='field'>תיאור קצר<textarea name='message' /></label></form></section></div></main>;
}
